# Generated by Django 2.0.1 on 2019-03-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('don_blood_group', models.CharField(max_length=20)),
                ('don_city', models.CharField(max_length=30)),
                ('don_mail', models.CharField(max_length=30)),
                ('don_contact', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_blood_group', models.CharField(max_length=20)),
                ('req_city', models.CharField(max_length=30)),
            ],
        ),
    ]
