# Generated by Django 2.0.1 on 2019-03-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='don_add',
            field=models.CharField(default='Hyderabad', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='req_add',
            field=models.CharField(default='Hyderabad', max_length=300),
            preserve_default=False,
        ),
    ]
